name: Run Telegram Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Tự động khởi động lại bot lúc 5h sáng hàng ngày

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start bot
        run: node bot.js
